### ISSUE TITLE
Let players know what chat groups they are speaking in

### ISSUE THREAD

**Issue by ItsSammyM** [mafia-rust/mafia#526] opened 2024-02-26 02:34 UTC
Also
When you can't speak out loud. It should show some icon so people know they aren't allowed to speak.

If you are allowed to speak in all chat, you are allowed to speak out loud

**Comment by Jack-Papel** [comment] 2024-02-27 19:18
Duplicate of #527?

**Closed** 2024-02-28 22:54 UTC
Labels: Duplicate, UI issue
